# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2istih442QoZxv9SWM0clpg3lPjtwhR
"""

!pip install nltk

import nltk
nltk.download('vader_lexicon')

import pandas as pd
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk

# Download VADER if not already
nltk.download('vader_lexicon')

# Load the CSV file
df = pd.read_csv('TestReviews.csv')  # Make sure this file exists in the same directory

# Inspect the dataset
print(df.head())

# Initialize the VADER sentiment analyzer
sia = SentimentIntensityAnalyzer()

# Define a function to get sentiment label
def get_sentiment(text):
    score = sia.polarity_scores(str(text))['compound']
    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"

# Apply the sentiment analysis
df['Sentiment'] = df['review'].apply(get_sentiment)

# Optional: View results
print(df[['review', 'Sentiment']].head())

# Save to new CSV
df.to_csv('reviews_with_sentiment.csv', index=False)